### ISSUE TITLE
cafetutorial_report_analysis.py报错

### ISSUE THREAD

**Issue by zhouyu98** [Github-Yilei/genome-assembly#1]
谢谢大佬的脚本，有个问题想请教下
运行cafetutorial_report_analysis.py的时候第193和175行报错
ValueError: invalid literal for int() with base 10: '_0'
cafe报告里检索'_0'是节点位置的1_0，删掉'_0'后报错
ValueError: invalid literal for int() with base 10: ''
请问这种情况处理呢？

**Comment by Github-Yilei** [comment]
抱歉，才看到  。 还需要帮助么？
